version: "3.7"
services:
  web:
    image: careapp/webapp-admin
    container_name: backend
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
    container_name: postgres
