name: test docker version
on: push 
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker buildx version
        run: docker buildx version
      - name: buildx
        run: chmod a+x ~/docker/cli-plugins/docker-buildx
            
