name: Publish Docker image

on:
  push:
    branches:
    - master
    paths:
    - 'docker-example/*'
    - '.github/workflows/docker-example.yml'
#ggg

jobs:
  push:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and tag image
      run: docker build -t "docker.pkg.github.com/zhuorg/dockertest/docker-windows:v2" -f Dockerfile .

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      shell: bash
      
    - name: Build fix
      run: docker build -t registry-windows:2.7.1-1809 -f Dockerfile2 .
      shell: bash
      
    - name: Publish to GPR
      run: docker push "docker.pkg.github.com/zhuorg/dockertest/docker-windows:v1"
      shell: bash
  pull:  
    runs-on: windows-latest
    steps:
    - run: |
         docker pull docker.pkg.github.com/zhuorg/dockertest/docker-windows:v2
    
