name: Publish Docker image

on:
  push:
    branches:
    - master
    paths:
    - 'docker-example/*'
    - '.github/workflows/docker-example.yml'
#ggg

jobs:
  push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and tag image
      run: docker build -t "docker.pkg.github.com/zhuorg/dockertest/docker-windows:$TAG" -f Dockerfile .
      env: 
        TAG: '6.0'
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      shell: bash
            
    - name: Publish to GPR
      run: docker push "docker.pkg.github.com/zhuorg/dockertest/docker-windows:$TAG"
      shell: bash
      env: 
        TAG: '6.0'
  pull:  
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      shell: bash 
    - run: |
         docker pull docker.pkg.github.com/zhuorg/dockertest/docker-windows:v2
    
