name: push docker image
on: 
  push: 
    branches: 
    - master
    paths: 
    - 'docker-example/*' 
    - '.github/workflows/dockerUbuntu.yml' 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v1 
    - run: |
        echo $github_ref   
        home_mf="${github_ref////-}"
        echo $home_mf
      env:
        github_ref: ${{ github.ref }}
    - name: Build and tag image 
      run: docker build -t "docker.pkg.github.com/zhu5201314/learnactions/docker-learn:$github_ref" -f docker-example/Dockerfile .
   # - name: Docker login 
   #   run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN 
   #   env: 
   #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
   # - name: Publish to GPR 
   #   run: docker push "docker.pkg.github.com/zhu5201314/learnactions/docker-learn:$GITHUB_SHA"
