name: login docker hub

on: 

  push: 

    branches: 

    - master

    paths: 

    - 'docker-example/*' 

    - '.github/workflows/dockerlogin.yml' 

jobs: 

  build: 

    runs-on: windows-2019
    strategy:
      matrix:
        # Needs to match python version of images (see windows-docker-image.yaml)
        python-version:
          - '2.7.17'
          - '3.6.8'
          - '3.7.5'

    steps: 

    
    - name: login docker hub 

      run: |
       ${gh_user} = ("${{ github.repository }}" -Split '/')[0]
       write-host ${gh_user}
       
       $user = 'yanjingzhu'
       #docker login -u $user --password-stdin ${{ secrets.DOCKERHUB_TOKEN }}  
       '${{ secrets.DOCKERHUB_TOKEN }}' | docker login -u $user --password-stdin
      env: 

          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    - name: matrix
      run: echo ${{ matrix.python-version }}
      shell: bash
