name: Docker Image CI

on: [push]

jobs:

 build:

  runs-on: windows-latest
 

  steps:
  - uses: actions/checkout@v1
  - name: Build the docker-compose stack
    run: docker-compose up -d
  #- name: Sleep
    #uses: jakejarvis/wait-action@master
    #with:
      #time: '60s'
  - name: Check running containers
    run: docker ps
   
