name: Docker Image CI

on: [check_suite]

jobs:

 build:

  runs-on: windows-latest   

  steps:
  - run: |
     & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon
  - uses: actions/checkout@v1
  - name: Build the docker-compose stack
    run: docker-compose up -d
  #- name: Sleep
    #uses: jakejarvis/wait-action@master
    #with:
      #time: '60s'
  - name: Check running containers
    run: docker ps -a
   
